general:
 // buildTool: 'npm'
 // gitSshKeyCredentialsId: 'credentials-id-in-jenkins'
  
steps:
  integrationArtifactDownload:
    cpiApiServiceKeyCredentialsId: ServiceKeyCredential
    integrationFlowId: AS2_Sender_Test
    integrationFlowVersion: 1.0.1
    downloadPath: ./iflows

  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: TrialServiceKey
    integrationFlowId: AS2_Sender_Test

  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: ServiceKeyCredential
    integrationFlowId: AS2_Sender_Test
