general:
 // buildTool: 'npm'
 // gitSshKeyCredentialsId: 'credentials-id-in-jenkins'
  
steps:
  integrationArtifactDownload:
    cpiApiServiceKeyCredentialsId: secretkeyunpd
    integrationFlowId: TEST_SOAP
    integrationFlowVersion: 1.0.1
    downloadPath: ./iflows
