general:

  
steps:
  integrationArtifactDownload:
    cpiApiServiceKeyCredentialsId: ServiceKeyCredential
    integrationFlowId: AS2_Sender_Test
    integrationFlowVersion: 1.0.1
    downloadPath: ./iflows

  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: TrialServiceKey
    integrationFlowId: AS2_Sender_Test

  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: TrialServiceKey
    integrationFlowId: AS2_Sender_Test
    integrationFlowName: AS2_Sender_Test
    packageId: TestAS2
    filePath: ./iflows/AS2_Sender_Test.zip
   
